### ISSUE TITLE
Discrepancies in Properties and Format within hocr_document_template.xml.j2

### ISSUE THREAD

**Issue by amehmood-pls** [googleapis/python-documentai-toolbox#156]
I'm trying to create the hOCR file using a JSON file that I generated through DocumentAI. However, it seems that the hocr_document_template.xml.j2 template anticipates a distinct structure. To elaborate, it requires paragraphs followed by nested lines within those paragraphs, with each line further containing nested words. In contrast, the JSON produced by DocumentAI doesn't adhere to this format. Moreover, the hocr_document_template.xml.j2 template utilizes dissimilar property names like hocr_bounding_box, which are absent in the JSON file (attached).

Adding to this, the code repository displays a templates folder at google/cloud/documentai_toolbox/templates/. Nonetheless, upon installing google.cloud.documentai_toolbox via pip, the templates folder appears to be missing.

[wikipedia-sample.json.txt](https://github.com/googleapis/python-documentai-toolbox/files/12292698/wikipedia-sample.json.txt)

**Comment by holtskinner** [comment]
For clarification, the [`Document`][1] object structure directly from Document AI doesn't follow the hOCR structure with lines nested inside paragraphs, etc. But the `Document` "wrapper" class within the Document AI Toolbox library does follow that nested structure as of [`v0.9.0-alpha`][2]. It can import a Document AI `Document` and convert it to the wrapped document structure, which can be exported into the hOCR format.

This code sample shows how to convert a Document AI `Document` JSON file into an hOCR string.

https://cloud.google.com/document-ai/docs/toolbox#hocr-conversion

As for the templates folder being missing: Can you try the sample code first and report back on if it works as expected?

[2]: https://github.com/googleapis/python-documentai-toolbox/releases/tag/v0.9.0-alpha

**Comment by amehmood-pls** [comment]
Thanks for the clarification. Upon executing the sample code, the following error is displayed.

Traceback (most recent call last):
  File "/home/am/ocr/hocr.py", line 26, in <module>
    hocr_string = convert_document_to_hocr_sample(document_path, document_title)
  File "/home/am/ocr/hocr.py", line 21, in convert_document_to_hocr_sample
    hocr_string = wrapped_document.export_hocr_str(title=document_title)
  File "/home/am/anaconda3/lib/python3.10/site-packages/google/cloud/documentai_toolbox/wrappers/document.py", line 769, in export_hocr_str
    loader=PackageLoader("google.cloud.documentai_toolbox", "templates")
  File "/home/am/anaconda3/lib/python3.10/site-packages/jinja2/loaders.py", line 323, in __init__
    raise ValueError(
ValueError: The 'google.cloud.documentai_toolbox' package was not installed in a way that PackageLoader understands.

**Comment by holtskinner** [comment]
I'm able to reproduce the behavior on my machine. Not sure why the samples tests didn't catch this. I'm going to keep investigating

Also, I noticed that the sample json you attached does not entirely follow the correct format, it looks like it was modified after processing by Document AI, because some fields have invalid values, like `pages.image`. Note - You also need to provide just the `document` part, not the full response JSON.

**Comment by amehmood-pls** [comment]
Uncertain about the invalid values like `page.image`. The JSON output remained unchanged subsequent to processing by Document AI. I created a processor based on Document OCR to produce the JSON.

**Comment by holtskinner** [comment]
Release 0.10.0-alpha should resolve the `PackageLoader` issue

**Comment by amehmood-pls** [comment]
Thank you, @holtskinner!
